version: '3'
services:
  prod:
    image: lionezajoao/nutri-website-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
