version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    deploy:
      mode: replicated
      replicas: 1

  prod:
    image: lionezajoao/nutri-website-prod:latest
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1

  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`xn--almoosemestresse-fpb.app.br`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    deploy:
      mode: replicated
      replicas: 1

networks:
  default:
    # external:
    #   name: traefik_public
    driver: overlay
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.web.rule=PathPrefix(`/`)"
    - "traefik.http.routers.web.entrypoints=web"
    - "traefik.http.services.app.loadbalancer.server.port=8000"
    - "traefik.http.routers.web.rule=Host(`xn--almoosemestresse-fpb.app.br/`)"
    - "traefik.http.routers.web.entrypoints=websecure"
    - "traefik.http.routers.web.tls.certresolver=leresolver"
