version: "3.3"

services:
  app:
    image: lionezajoao/nutri-website:latest
    build: .
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - .:/usr/src/app

    networks:
      - default
networks:
  default:
    driver: overlay