version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    deploy:
      mode: replicated
      replicas: 1

  prod:
    image: lionezajoao/nutri-website-prod:latest
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prod.rule=Host(`xn--almoosemestresse-fpb.app.br`)"
      - "traefik.http.routers.prod.entrypoints=websecure"
      - "traefik.http.routers.prod.tls.certresolver=myresolver"
      - "traefik.http.services.prod.loadbalancer.server.port=8000"

networks:
  default:
    external:
      name: traefik_public
