version: "3.3"

services:
  traefik:
    image: "traefik:v2.11"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      
  service:
    image: lionezajoao/nutri-website-prod:latest
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prod.rule=Host(`xn--almoosemestresse-fpb.app.br`)"
        - "traefik.http.routers.prod.entrypoints=websecure"
        - "traefik.http.routers.prod.tls.certresolver=myresolver"
        - "traefik.http.services.prod.loadbalancer.server.port=8000"
    ports:
      - "8000:8000"
    networks:
      - traefik_public

networks:
  default:
    external:
      name: traefik_public
