[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http.redirections]
            [entryPoints.web.http.redirections.entryPoint]
                to = "websecure"
                scheme = "https"
    [entryPoints.websecure]
        address = ":443"

[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    network = "traefik_public"

[certificatesResolvers.myresolver.acme]
    email = "joaopedrobzlioneza@gmail.com"
    storage = "/letsencrypt/acme.json"
    [certificatesResolvers.myresolver.acme.httpChallenge]
        entryPoint = "web"

[api]
    dashboard = false

[log]
    level = "DEBUG"
