name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env.prod file
        run: |
          echo "PG_HOST=${{ secrets.PG_HOST }}" >> .env.prod
          echo "PG_DATABASE=${{ secrets.PG_DATABASE }}" >> .env.prod
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env.prod
          echo "PG_PASS=${{ secrets.PG_PASS }}" >> .env.prod
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env.prod
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env.prod
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env.prod
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env.prod
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env.prod
          echo "TOKEN_KEY=${{ secrets.TOKEN_KEY }}" >> .env.prod
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.prod
          echo "GURU_TOKEN=${{ secrets.GURU_TOKEN }}" >> .env.prod
          echo "NEW_USR_PWD=${{ secrets.NEW_USR_PWD }}" >> .env.prod

      - name: Transfer .env.prod file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: .env.prod
          target: ~/nutri-website

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nutri-website:latest -f prod.Dockerfile .

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nutri-website:latest

      - name: Update Docker Swarm Service and Pull Changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd ~/nutri-website
            git pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/nutri-website:latest
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/nutri-website:latest nutri-website_service
            docker system prune --all --force
